---
- name: "check if docker installer exist"
  stat:
    path: "~/Downloads/Docker.dmg"
  register: docker_download_status
  ignore_errors: True

- name: "download docker for mac intel"
  get_url:
    url: "{{ url.x86_64 }}"
    dest: "/Users/{{ lookup('env', 'USER') }}/Downloads/Docker.dmg"
  when: docker_download_status.stat.exists == False and ansible_machine == "x86_64"

- name: "download docker for mac m1"
  get_url:
    url: "{{ url.arm64 }}"
    dest: "/Users/{{ lookup('env', 'USER') }}/Downloads/Docker.dmg"
  when: docker_download_status.stat.exists == False and ansible_machine == "arm64"

- name: "install docker"
  command: "{{ item }}"
  loop:
  - "hdiutil attach /Users/{{ lookup('env', 'USER') }}/Downloads/Docker.dmg"
  - "/Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license"
  - "hdiutil detach /Volumes/Docker"
  become: True
