---
- name: "Create a vscode setting file"
  template:
    src: vscode-settings.json.j2
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: install extensions
  shell: code --install-extension {{ item }}
  with_items:
  - golang.go
  - hashicorp.terraform
  - eriklynd.json-tools
  - redhat.ansible
  - ahebrank.yaml2json
