---
- name: "Make sure homebrew bin is in path"
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: "/opt/homebrew/bin"
  become: true
  become_user: root

- name: "Install homebrew packages"
  community.general.homebrew:
    name:
    - "{{ item }}"
    state: present
    update_homebrew: yes
  loop: "{{ homebrew_packages }}"

- name: install rosetta for mac m1
  shell: softwareupdate --install-rosetta --agree-to-license
  become: true
  when: ansible_machine == "arm64"

- name: "Install core packages via brew casks"
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: true
  loop: "{{ homebrew_cask }}"
