homebrew_packages:
- aws-iam-authenticator
- awscli
- azure-cli
- go
- graphviz
- htop
- kubernetes-cli
- nvm
- romkatv/powerlevel10k/powerlevel10k
- telnet
- terraform
- zsh

homebrew_cask:
- appcleaner
- bitwarden
- brave-browser
- chrome-remote-desktop-host
- discord
- firefox
- google-chrome
- iterm2
- keybase
- ledger-live
- nordvpn
- notion
- postman
- robo-3t
- sourcetree
- spotify
- tableplus
- telegram
- virtualbox
- visual-studio-code
- vlc
- wechat
- whatsapp
- zoom